version: "3.9"

services:
  smartfinancial-ai:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: smartfinancial-ai
    ports:
      - "8501:8501"
    volumes:
      - ../sample_data:/app/sample_data
    restart: unless-stopped
